### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by samjett247** [stev-ou/stev-api#3]
- [ ] Separate data loading and api server components into separate folders
- [x] Fix apis to serve content in order of term code

**Comment by zachschuermann** [comment]
- [ ] Cloud Storage Integration
- [ ] Load Testing

**Comment by samjett247** [comment]
- [x] Running OCR to get acceptable dataset
- [ ] Changing the APIs such that instead of serving from a set list of semesters (Currently, serves S, SU, and F from 2016,2017, 2018), the APIs will serve based on the available data for that search request (i.e. if we only have data from 2017 and back, maybe we serve 2015, 2016, and 2017?
- [ ] Piping data from the OCR database documents to pass into data aggregation and generate documents inside the ou-reviews db for querying

- These are for you if thats cool @jlovoi
